### ISSUE TITLE
App constantly restarting

### ISSUE THREAD

**Issue by chi-mdurham** [maximlink/managed-view#4] opened 2020-10-27 23:24 UTC
On iOS 14 the app constantly restarts, has anyone else run into this?

**Comment by tobiaslinder** [comment] 2020-11-02 21:02
Same here sadly.

**Comment by maximlink** [comment] 2020-11-02 21:59
I am having trouble reproducing this. Can you provide your appconfig?

**Comment by maximlink** [comment] 2020-11-02 22:01
Are you using the Apple app store version or building your own?

**Comment by chi-mdurham** [comment] 2020-11-02 22:02
Using the app store version deployed via Jamf Pro

Here is my appconfig:

<dict>
  <key>MAINTENANCE_MODE</key>
    <string>OFF</string>
  <key>URL</key>
    <string>https://www.dayforcehcm.com/clock/index.html</string>
  <key>BROWSER_MODE</key>
    <string>ON</string>
   <key>BROWSER_BAR_NO_EDIT</key>
     <string>OFF</string>
</dict>

**Comment by chi-mdurham** [comment] 2020-11-02 22:27
`<dict>
  <key>MAINTENANCE_MODE</key>
    <string>OFF</string>
  <key>URL</key>
    <string>https://www.dayforcehcm.com/clock/index.html</string>
  <key>BROWSER_MODE</key>
    <string>ON</string>
   <key>BROWSER_BAR_NO_EDIT</key>
     <string>OFF</string>
</dict>`

**Comment by maximlink** [comment] 2020-11-10 00:01
If you can get me the crash report from the device, that would be awesome.

Settings>Privacy>Analytics & Improvements>Analytics Data> The crash report should be called Managed View <timestamp>.ips.

E-mail to managed-view@jamf.com

thanks in advance.

**Comment by tobiaslinder** [comment] 2020-11-10 07:35
Hi 
I had no success in sending you the crash report because of that:

"The group managed-view only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."
 
but here I have the report for you:

https://ewolke.ch/index.php/f/163454495

**Comment by maximlink** [comment] 2020-11-12 19:41
Thank you for the crash report. I believe the issue is fixed with version 2.1.2. Not in App Store yet, but available via public TestFlight link.

 https://testflight.apple.com/join/znq7lSDN

If testFlight build is installed on device with Managed View already installed and managed by Jamf, then the appconfig will be used.

Any feedback would be appreciated.

Thanks.

**Comment by maximlink** [comment] 2020-11-13 00:10
Thank for sending the crash report. It helped greatly. New version (2.1.2) now available in the App Store.

**Comment by tobiaslinder** [comment] 2020-11-13 15:39
Hey @maximlink 
thank you so much. That version works perfectly. And I just figured out that I can actually enter the URL in an extension attribute and send the variable into the app config. This is a perfect solution for a use case with a company that has iPads in use for the management of her infrastructure and every iPad needs another URL for the management console.

**Comment by maximlink** [comment] 2020-11-14 01:59
@tobiaslinder Thank you for the loopback!

Awesome to hear how you are leveraging Jamf Pro extension attribute variables. One of my personal favorite features of AppConfig. 

Best of luck

**Comment by 3enjam** [comment] 2021-04-26 16:22
Hello - this has been working great for me on older ios but I seem to be having this issue on 14..4.x rinnung version 56 (2.2)
I have tried both MDM & app store installs but get Exception Type:  EXC_CRASH (SIGABRT) in crash logs. I can provide if it helps.

**Comment by maximlink** [comment] 2021-04-26 17:44
Hello @3enjam 

Please send me the crash log. Also, the app config xml would be very helpful. 

Settings>Privacy>Analytics & Improvements>Analytics Data> The crash report should be called Managed View .ips.

E-mail to managed-view@jamf.com

thanks in advance.

**Comment by 3enjam** [comment] 2021-04-27 11:29
Thank you @maximlink for the reply. I have emailed to the address above.

**Closed** 2021-06-14 17:45 UTC
